---
documentclass: scrartcl
lang: es
geometry: 
- top=1.5cm
- bottom=1.5cm
- left=1.5cm
- right=1.5cm
#mainfont: Arial #LiberationSans
fontfamily: palatino
fontsize: 10pt
#bibliography: bibliografia.bib
colorlinks: true
---

